import sidechainnet as scn
import numpy as np

seq = 'MSNISLIVGLGNPGSEYAQTRHNAGFWFVEQLADKYGITLKNDPKFHGISGRGNIEGHDVRLLLPMTYMNRSGQSVVPFSKFYQIAPEAILIAHDELDMNPGVIRLKTGGGHGGHNGLRDIVPHIGPNFHRLRIGIGHPGSKERVSGHVLGKAPSNEQSLMDGAIDHALSKVKLLVQGQVPQAMNQINAYKPA'
crd = np.random.uniform(low = -10, high = 10, size = (len(seq*14),3))
sb2 = scn.StructureBuilder(seq, crd)
s = sb2.to_3Dmol()
s.png()